export const LAYOUT = {
  TOGGLE_SIDEBAR_DESKTOP: "TOGGLE_SIDEBAR_DESKTOP",
  TOGGLE_SIDEBAR_MOBILE: "TOGGLE_SIDEBAR_MOBILE",
  SET_SIDEBAR: "SET_SIDEBAR",
  SET_LOADING: "SET_LOADING"
};

export const AUTH = {
  AUTH_LOGIN: "AUTH_LOGIN",
  FETCH_AUTH: "FETCH_AUTH",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_FORGOT_PASSWORD_REQUEST: "AUTH_FORGOT_PASSWORD_REQUEST",
  AUTH_FORGOT_PASSWORD_RESET: "AUTH_FORGOT_PASSWORD_RESET"
};

export const EMPLOYEE = {
  FETCH_EMPLOYEE: "FETCH_EMPLOYEE",
  SHOW_EMPLOYEE: "SHOW_EMPLOYEE",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  GET_EMPLOYEE: "GET_EMPLOYEE",
  GET_INFO_EMPLOYEE: "GET_INFO_EMPLOYEE"
};

export const COMMONS = {
  FOOTS: "FOOTS",
  DIVISIONS: "DIVISIONS",
  POSITIONS: "POSITIONS",
  JOBTITLE: "JOBTITLE",
  WORKTYPE: "WORKTYPE",
  COMPANIES: "COMPANIES"
};

export const CHART = {
  MEMBER_COMPANIES: "MEMBER_COMPANIES",
  MEMBER_FOOTS: "MEMBER_FOOTS",
  MEMBER_DIVISIONS: "MEMBER_DIVISIONS",
  MEMBER_JOB_TITLE: "MEMBER_JOB_TITLE",
  MEMBER_IN_OUT: "MEMBER_IN_OUT"
};

export const SET_LOCALE = "SET_LOCALE";

export const CUSTOMER = {
  FETCH_CUSTOMER: "FETCH_CUSTOMER",
  DETAIL_CUSTOMER: "DETAIL_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  CREATE_CUSTOMER: "CREATE_CUSTOMER"
};
